Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -224,19 +224,17 @@ jobs:
           BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
           BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
         run: |
-          RET=`curl --write-out '|%{content_type}' --output /dev/null --request GET --user ${BASIC_AUTH_USER}:${BASIC_AUTH_PASS} --url ${TEST_STARTER_URL}`
+          RET=`curl --write-out '|%{content_type}' --request GET --user ${BASIC_AUTH_USER}:${BASIC_AUTH_PASS} --url ${TEST_STARTER_URL}`
           IFS='|' read -ra RESULTS <<< "$RET"
-          if [ ${RESULTS[0]}=="text/html" ]
-            then
-              echo "Received content_type is ${RET}, was expecting application/json or application/zip"
-              exit 1
-            else
-              if [ ${RESULTS[0]}=="application/zip" ]
-                then
-                  echo "Error(s) found!"
-                  exit 1
-              fi
-              echo "${RESULTS[1]}"
+          if [ "${RESULTS[1]}" = "application/zip" ]; then
+            echo "Failed Integration Test(s) found!"
+            exit 1
+          fi
+          if [ "${RESULTS[1]}" = "application/json" ]; then
+            echo "${RESULTS[0]}"
+          fi
+          if [ "${RESULTS[1]}" != "application/zip" ] && [ "${RESULTS[1]}" != "application/json" ]; then
+            echo "Received content_type is ${RESULTS[1]}, was expecting application/json or application/zip"
           fi
 
       - name: Archive production artifacts
